package org.titilda.music.base.model;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Objects;
import java.util.UUID;

/**
 * Model class representing a PlaylistSong (junction table) in the music application.
 * This represents the relationship between a Playlist and a Song with position information.
 */
public class PlaylistSong {
    private Integer id;
    private UUID playlistId;
    private UUID songId;
    private Integer position;

    // Default constructor
    public PlaylistSong() {}

    // Constructor with all fields except id (for new playlist songs)
    public PlaylistSong(UUID playlistId, UUID songId, Integer position) {
        // Note: ID is auto-generated by database (IDENTITY column)
        this.playlistId = playlistId;
        this.songId = songId;
        this.position = position;
    }

    // Constructor with all fields including id (for existing playlist songs)
    public PlaylistSong(Integer id, UUID playlistId, UUID songId, Integer position) {
        this.id = id;
        this.playlistId = playlistId;
        this.songId = songId;
        this.position = position;
    }

    // Getters and Setters
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public UUID getPlaylistId() {
        return playlistId;
    }

    public void setPlaylistId(UUID playlistId) {
        this.playlistId = playlistId;
    }

    public UUID getSongId() {
        return songId;
    }

    public void setSongId(UUID songId) {
        this.songId = songId;
    }

    public Integer getPosition() {
        return position;
    }

    public void setPosition(Integer position) {
        this.position = position;
    }


}
